apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cath-cert
spec:
  dnsNames:
  - cath.njk.onl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: cath-cert
