apiVersion: apps/v1
kind: Deployment
metadata:
  name: cath
spec:
  selector:
    matchLabels:
      app: cath
  template:
    metadata:
      labels:
        app: cath
    spec:
      containers:
      - name: cath
        image: rg.nl-ams.scw.cloud/njkonl/cath:0.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1  
kind: Service
metadata:
  name: cath
spec:
  selector:
    app: cath
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cath
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: cath.njk.onl
    http:
      paths:
      - path: /
        backend:
          serviceName: cath
          servicePort: 80
  tls:
  - hosts:
    - cath.njk.onl
    secretName: cath-cert
